### PR TITLE
Updated setRelation method to remove cid from link object

### PR DESCRIPTION
**Pull request by jrotolo**
When using setRelation to set a relationship on a bb model the relationship was not valid because linkageForObject was adding the cid field on to the relationship link object. A relationship link object is suppose to be in the form data: {id: 1, type: 'examples'}

### CODE REVIEW

**Comment by prehnRA** [comment]
What issue was this causing? If it is an issue with the JSON we send up to the server, we should fix it at the spot where we make that JSON.

The reason this is here is to handle relations to unsaved models until the time they get real IDs.

**Comment by jrotolo** [comment]
So the issue is if I use setRelation to add a relation to an unsaved model and then later go to save that model the save will fail. It fails because in the relationship  links there is an extra field ('cid'). I found out that this cid field is being added in this method. We can't save a model with this field in its relationship data. I could do the omit right before the JSON is sent up to the server, but then I would always have to do that on the application side if I ever use setRelation. Shouldn't setRelation set a valid relationship?

**Comment by prehnRA** [comment]
You don't always have to do it on the application side. If we change BaseModel in revelry_data, it'll apply to all models in all the apps.

**Comment by jrotolo** [comment]
@prehnRA So I did some digging into BaseModel and was going to to edit the toJSON to omit the cid from relationships, but as I was debugging I found `linkageAttributes()` method was explicitly setting the cid attribute. The JSONAPI spec doesn't allow for any extra attributes in a resource identifier besides id, type, and a meta member.  http://jsonapi.org/format/#document-resource-identifier-objects

**Pull request closed without merging**
