### PR TITLE
DNM F StoreForm afterSubmit call

### PR DESCRIPTION
**Pull request by Harleymckee**
Attached onSubmit wasn't getting called on StoreForm. I passed the function through props to the StoreForm onSubmit handler.

### CODE REVIEW

**Comment by prehnRA** [comment]
1. What do we use this for?

2. I assume we would want the onSubmit to actually get triggered after the save is done, right? Otherwise if the onSubmit does something like navigate to a different page, our save request could be interrupted.

**Comment by Harleymckee** [comment]
@prehnRA yeah I wanted an after save handler to attach a newly created customer to the local event instance (need customer id) for https://github.com/revelrylabs/spacewalk/pull/199

Is this useful for rev_data? or should I override at spacewalk somehow?

**Comment by prehnRA** [comment]
@Harleymckee Could you use a sync event on the customer? It should fire after the save is complete, when the customer has an id.

**Comment by Harleymckee** [comment]
ok cool thanks

**Pull request closed without merging**
